# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Juan Antonio Pardo Robles
email: japardorobles.contact@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal site where you can find some of my projects, enjoy it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://japardorobles.github.com" # the base hostname & protocol for your site
github_username:  japardorobles

# Build settings
markdown: kramdown
